### ISSUE TITLE
Minimum version of Rustc missing from documentation

### ISSUE THREAD

**Issue by jahway603** [matrix-org/rust-synapse-compress-state#110]
I am able to build this with rustc 1.64.0 on one system but am unable to build using rustc 1.48.0 (which is the default in Debian 11 repo). What is the minimum required version of rustc to build this?

**Comment by H-Shay** [comment]
We don't have a specific version that is required, this project follows the same dependency policy as Synapse (which can be found at https://matrix-org.github.io/synapse/latest/deprecation_policy.html), where the relevant lines are: "A Rust compiler is required to build Synapse from source. For any given release the minimum required version may be bumped up to a recent Rust version, and so people building from source should ensure they can fetch recent versions of Rust (e.g. by using [rustup](https://rustup.rs/))."

**Comment by gdt** [comment]
As the packager for synapse in pkgsrc, I will note:
  - not declaring dependencies is unfriendly, and it's a bug not a feature that synapse is like this.  It feels like "we have no idea what version is required and if it doesn't build you can figure out if there's a bug or your rust isn't new enough".
  - rust is in general difficult to deal with (on other than a few popular systems and on those the popular CPUs), so it's better to tread as lightly as possible in requiring recent rust.
  - rustup only works if rust.org publishes official binaries (surely this must be true), and there are platforms that can run rust but not rustup
