### ISSUE TITLE
Cargo build fails due to Cargo.toml configuration

### ISSUE THREAD

**Issue by gspbirel56** [matrix-org/rust-synapse-compress-state#121]
Hello, after a fresh pull from the repo, following the readme's build instructions gave me the following error:
```
error: failed to parse manifest at `/[...]/rust-synapse-compress-state/synapse_auto_compressor/Cargo.toml`

Caused by:
  Features and dependencies cannot have the same name: `pyo3`
```

**Comment by H-Shay** [comment]
Hmm, I was unable to reproduce this on my machine - what version cargo are you using? What operating system?

**Comment by gspbirel56** [comment]
Hi @H-Shay! I realized my mistake. I only installed rustc from apt (Debian) and I did not have the complete set of tools to compile a Rust application. I twas able to get up and running after installing Rust from the official shell script.
