### ISSUE TITLE
Incorrect example usage in README

### ISSUE THREAD

**Issue by PaarthShah** [matrix-org/rust-synapse-compress-state#125]
As of compiling the current latest, I'm seeing the following in `--help`:
```
Usage: synapse_compress_state [OPTIONS] -p <POSTGRES_LOCATION> -r <ROOM_ID>
```

Which is inconsistent with an example usage shown in the README (which is missing the required `-r` parameter): https://github.com/matrix-org/rust-synapse-compress-state/blob/8dc70fec8df33639bab1733bc88a40c1ed0f20b3/README.md#example-usage
```
synapse_auto_compressor -p postgresql://user:pass@localhost/synapse -c 500 -n 100
```

**Comment by reivilibre** [comment]
I believe `synapse_compress_state` and `synapse_auto_compressor` are different tools both packaged in this repository — if I remember properly, the auto compressor automatically finds rooms that could benefit from optimisation and then applies the compressor on those automatically, whereas the `synapse_compress_state` tool wants you to specify a tool yourself.

**Comment by PaarthShah** [comment]
That makes a lot of sense, oops!
