### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by RodrigoTjader** [matrix-org/rust-synapse-compress-state#17]
Hello,

I'm trying to build this to run on my synapse instance, but I'm getting the following error:

```
# cargo build
error: failed to parse lock file at: /root/rust-synapse-compress-state/Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`
```

I'm not experienced with Rust, so I may be doing something wrong. I have tried removing Cargo.lock before building, but that leads to many compilation errors.

It would also be nice if a precompiled version was available here on github.

**Comment by anoadragon453** [comment]
Thanks for reporting @RodrigoTjader. Could you also post your `cargo` and `rustc` versions?

```
cargo -V
rustc -V
```

**Comment by RodrigoTjader** [comment]
I'm running on Debian 10:

```
# cargo -V
cargo 1.34.0
# rustc -V
rustc 1.34.2
```

**Comment by erikjohnston** [comment]
We debugged this on Matrix, and basically the rustc version is too old. I need to and figure out what the minimum required version is and will add to README.

(FTR, the easiest way of getting an up to date rustc is via rustup.rs)
