### ISSUE TITLE
Should synapse be shut down while running this?

### ISSUE THREAD

**Issue by turt2live** [matrix-org/rust-synapse-compress-state#2]

**Comment by richvdh** [comment]
It should be fine to leave it running.

**Comment by turt2live** [comment]
including the sql at the end?

**Comment by richvdh** [comment]
indeed.

To give some more details, the `state_groups` and `state_groups_state` tables are append-only: once written to the database, they are never modified. There is therefore no danger of a modification racing against a running synapse. Further, this script makes its changes within atomic transactions, and each transaction should not affect the results from any of the queries that synapse performs.

**Comment by turt2live** [comment]
That's pretty cool. I'll leave this open as a reminder to someone (probably myself) to add a quick note to the readme about that.

Thanks for the replies!
