### ISSUE TITLE
release is overdue

### ISSUE THREAD

**Issue by gdt** [matrix-org/rust-synapse-compress-state#95]
The most recent release is v0.1.0 on May 28, 2020.

I would like to create a package for this in pkgsrc, and clearly a lot of work has been done in the last two years.   Packaging systems usually have  a guideline of packging releases rather than snapshots.

Please tag a new release, so that users and packagers can have a suggested starting point.

**Comment by DMRobertson** [comment]
> The most recent release is v0.1.0 on May 28, 2020.

There is a [v0.1.2 tag](https://github.com/matrix-org/rust-synapse-compress-state/tags) from 6 Oct 2021 but it looks like that didn't get a release, and i think https://github.com/matrix-org/rust-synapse-compress-state/commit/0111079153c16fb98c7da417f298143747cd9e2c was effectively a v0.1.1 "release".

I'll do a 0.1.2 release and then make a 0.1.3 tag + release.

**Comment by DMRobertson** [comment]
See https://github.com/matrix-org/rust-synapse-compress-state/releases/tag/v0.1.2 and https://github.com/matrix-org/rust-synapse-compress-state/releases/tag/v0.1.3.

**Comment by gdt** [comment]
Thank you very much for tagging a release so quickly.
